
QZFL.config.gbEncoderPath="http://qzs.qq.com/qzone/v5/toolpages/";QZFL.config.FSHelperPage="http://qzs.qq.com/qzone/v5/toolpages/fp_gbk.html";QZFL.config.defaultShareObject="http://qzs.qq.com/qzone/v5/toolpages/getset.swf";QZFL.config.staticServer="http://qzs.qq.com/ac/qzone/qzfl/lc/";QZFL.widget.msgbox.cssPath="http://qzonestyle.gtimg.cn/ac/qzfl/release/css/msgbox.css";window.V=window.V||{};V.dialog=V.dialog||(function(){function show(title,content,width,height,opt){opt=opt||{};var useTween=opt.useTween,noBorder=opt.noBorder,callback=opt.callback;var _dialog=QZFL.dialog.create(title,content,width,height,useTween,noBorder);var _maskID=QZFL.maskLayout.create();_dialog.onUnload=function(){if(typeof callback=='function'){callback();}
QZFL.maskLayout.remove(_maskID);};return _dialog;}
return{show:show};})();V.login=V.login||(function(){var _RET_HASH={'SUCCESS':0,'FAIL':1,'CANCEL':2};var _dialog=null;var _targetWindow=null;var _sUrl='';var _appCallback=null;function _callback(ret){if(_appCallback){_appCallback(ret);if(ret===_RET_HASH['SUCCESS']){_appCallback=null;hide();}}else{if(ret===_RET_HASH['SUCCESS']){if("function"==typeof window.__logCallBackFn){window.__logCallBackFn();}else{_targetWindow.location.reload();}}else if(ret===_RET_HASH['FAIL']){hide();alert('登录失败');}}}
function _dialogCallback(){if(_appCallback){_appCallback(_RET_HASH['CANCEL']);}}
function show(opt){opt=opt||{};var _html='<iframe scrolling="no" style="width: 376px; height: 356px;" frameborder="0" allowtransparency="yes" src="http://e.qq.com/temp.html"></iframe>';_targetWindow=opt.targetWindow||window;_sUrl=opt.sUrl||location.href;_appCallback=typeof opt.callback=='function'?opt.callback:null;_dialog=V.dialog.show('登录',_html,376,325,{callback:QZFL.event.bind(this,_dialogCallback)});}
function hide(){_dialog.unload();}
function exit(target){QZFL.object.each(['uin','skey','zzpaneluin','zzpanelkey'],function(value){QZFL.cookie.set(value,'');});target?window.location.href=target:window.location.reload();}
function resize(w,h){if(_dialog){_dialog.setSize(w,h);}}
function getUin(){var uin=QZFL.cookie.get('uin')||QZFL.cookie.get('zzpaneluin');if(uin.length>4){return+uin.replace(/o(\d+)/g,'$1');}
return 0;}
function getUinsInfo(uins,callback){var _url='http://r.qzone.qq.com/fcg-bin/cgi_get_score.fcg?mask=4&uins=';var g=new QZFL.JSONGetter(_url+uins.join(','),Math.random().toString(),null);g.onSuccess=function(o){callback(o);};g.onError=function(){return;};g.send('portraitCallBack');}
function call(opt){var callback;opt=opt||{};if(getUin()){opt.callback&&opt.callback();return;}
if(opt.callback){callback=opt.callback;opt.callback=function(ret){if(ret==_RET_HASH['SUCCESS']){callback();opt.onLoginSuccess&&opt.onLoginSuccess();}else if(ret==_RET_HASH['CANCEL']){opt.onLoginCancel&&opt.onLoginCancel();}else{opt.onLoginFail&&opt.onLoginFail();}};}
show(opt);}
return{_callback:_callback,RET_HASH:_RET_HASH,show:show,hide:hide,exit:exit,resize:resize,getUin:getUin,getUinsInfo:getUinsInfo,call:call};})();var gdtDomin='e.qq.com';var GDTportalUser=function(){function generateHtmlStr(tagName,className,htmlStr,otherObj){var needClose=!(tagName=='input');var h;if(!otherObj){h='<'+tagName+' class="'+className+'">'+htmlStr;}else{var a='';QZFL.object.each(otherObj,function(v,k){a+=k+'="'+v+'" ';});h='<'+tagName+' class="'+className+'" '+a+' >'+htmlStr;}
if(needClose){h+='</'+tagName+'>'}
return h;}
var here={};here._stateValid=1;here._regPage='/regist.html';here._accountPage='/account.html';here.userInfo=null;var cookieV=['uin','skey','zzpaneluin','zzpanelkey'];here.cgiGetUserInfo=function(data,onSuccess,onError){var cgiUrl='http://'+gdtDomin+'/ec/loginfo.php';QBL.getter(cgiUrl,data,onSuccess,{errcbFn:onError,ozid:410190,noDefErr:1});};here.showLoginUserInfoAndControl=function(o,cb){var info=o.data;here.userInfo=info;var htmlStr='';var userName=generateHtmlStr('span','name',QZFL.string.cut(info.uname,8,'..'),{});userName+='<b class="ui_trig ui_trig_b"></b>';var dropLi='<li><a href="javascript:;" onclick="GDTportalUser.logout();return false;">退出</a></li>';var enter='';if(info.targettype!=14){if(info.status==0){here._managePage=here._regPage;enter=generateHtmlStr('a','','注册',{href:here._regPage});}else{here._managePage=info.homepage;enter=generateHtmlStr('a','','管理中心',{href:info.homepage});}}else{if(info.status!=0){here._managePage=info.homepage;enter=generateHtmlStr('a','','管理中心',{href:info.homepage});}else{here._managePage=here._regPage;}}
htmlStr=generateHtmlStr('a','user_name',userName,{'id':'_username',href:'javascript:;'})+enter+
generateHtmlStr('ul','user_op',dropLi,{'style':'display:none'});$e(here._userCorner).setHtml(htmlStr);cb&&cb();here._userInfoCallback&&here._userInfoCallback(o);};here.showNeedLogin=function(){var enter=generateHtmlStr('a','','登录',{href:'javascript:;',onclick:'GDTportalUser.login();return false;'});$e(here._userCorner).setHtml(enter);here._userInfoCallback&&here._userInfoCallback(null);};here.bindUserCornerActions=function(){var isDropDownOpen=false;var addE=QZFL.event.addEvent;var username=$e('#_username').eq(0);var drop=$e(here._userCorner).find('.user_op');addE(username,'mouseover',function(){$e(username).addClass('user_name_op');});addE(username,'mouseout',function(){if(!isDropDownOpen){$e(username).removeClass('user_name_op');}});$e(username).find('a,b,span').each(function(ele){addE(ele,'click',function(){if(isDropDownOpen){drop.hide();isDropDownOpen=false;}else{drop.show();isDropDownOpen=true;}
QZFL.event.cancelBubble();});});addE(username,'click',function(){if(isDropDownOpen){drop.hide();isDropDownOpen=false;}else{drop.show();isDropDownOpen=true;}
QZFL.event.cancelBubble();});addE(document.body,'click',function(evt){var tar=QZFL.event.getTarget(evt);if(isDropDownOpen&&!QZFL.dom.isAncestor(drop.eq(0),tar)){drop.hide();$e(username).removeClass('user_name_op');isDropDownOpen=false;}});};here.getUserInfo=function(cb){here.cgiGetUserInfo({},function(o){if(o.ret==0){here.showLoginUserInfoAndControl(o,cb);}else{here.showNeedLogin();}})};here.login=function(options){options=options||{};var sUserAgent=navigator.userAgent.toLowerCase(),isIphoneOs=(sUserAgent.match(/iphone os/i)==true),isAndroid=(sUserAgent.match(/android/i)==true),_sUrl=options.goto||window.location.href,styleCode,opt;if(isIphoneOs||isAndroid){styleCode=isIphoneOs?8:9;opt={style:styleCode,low_login_enable:0,hln_css:'http://imgcache.qq.com/open_proj/img/gdt/e_logo.png',s_url:_sUrl,appid:'15000103',callback:options.callback||null};window.V.login.loginPhone(opt);}else{opt={sUrl:_sUrl,callback:options.callback||null};window.V.login.show(opt);}};here.logout=function(){window.V.login.exit();here.showNeedLogin();here.logoutCallback&&here.logoutCallback();};here.logoutCallback=function(){window.location.reload();};here.isLogin=function(){var uin=QZFL.cookie.get('uin')||QZFL.cookie.get('zzpaneluin');if(uin.length>4){return+uin.replace(/o(\d+)/g,'$1');}
return 0;};here.sendPv=function(){var addr=location.pathname;QBL.monitorPV.report('gdt.qq.com','portal_'+addr);};here.init=function(options){options=options||{};here._options=options;here._userInfoCallback=options.userInfoCallback||null;here._userCorner=options.userCorner;try{document.domain='qq.com'}catch(e){}
var safe=true;(function(){try{if(!/^http(s)?:\/\/[.\w-]+((\.qq)|(\.pengyou))\.com\//i.test(document.referrer)){if(parent!=self){safe=false;throw new Error("can't be iframed");}}}catch(e){window.open(location.href,"_top")}})();if(safe){if(here.isLogin()){here.getUserInfo(here.bindUserCornerActions);}else{here.showNeedLogin();}
if(!options.noPv){here.sendPv()}}};return here;}();